# Site settings
title: Oshlack Lab at Peter Mac
email: alicia.oshack [at] petermac.org
description: > # this means to ignore newlines until "baseurl:"
    The Oshlack Lab at the Peter MacCallum Cancer Centre uses computational and statistical techniques to analyse and explore the transcriptome and genome.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://oshlack.github.io/" # the base hostname & protocol for your site
twitter_username: AliciaOshlack
github_username:  Oshlack
# Build settings
markdown: kramdown
