# Site settings
title: Oshlack Lab
email: alicia.oshacl [at] mcri.edu.au
description: > # this means to ignore newlines until "baseurl:"
    The Bioinformatics research group at MCRI focuses on statistical bioinformatics and computational biology. We work on analysis methods for high-throughput sequencing and microarrays and we are involved in many collaborative projects.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://oshlack.github.io/" # the base hostname & protocol for your site
twitter_username: AliciaOshlack
github_username:  Oshlack
# Build settings
markdown: kramdown
