# Site settings
title: Oshlack Lab
email: alicia.oshack [at] mcri.edu.au
description: > # this means to ignore newlines until "baseurl:"
    The bioinformatics research group at MCRI uses computational and statistical techniques to analyse and explore the transcriptome and genome.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://oshlack.github.io/" # the base hostname & protocol for your site
twitter_username: AliciaOshlack
github_username:  Oshlack
# Build settings
markdown: kramdown
